### ISSUE TITLE
裁剪结果中包含不可能被渲染器调用到的 glyph

### ISSUE THREAD

**Issue by 0tkl** [AmusementClub/AssFontSubset#13]
（字幕文件只有一行字幕，这一行只包含一个字母 `A`）

裁剪 HarmonyOS Sans SC 输出的字体额外带上了字母 ligature 和数字变体。

![image](https://github.com/AmusementClub/AssFontSubset/assets/118708188/abe85069-bb56-4599-9e2c-8f044e37b171)

[使用 Harfbuzz 后端时，libass 渲染器支持的 OpenType 特性](https://github.com/libass/libass/blob/0.17.1/libass/ass_shaper.c#L151-L174)包括 vert、vkna、kern、liga 和 clig。与 libass 相比，VSFilter 各分支支持的特性要么一致、要么更少。

也就是说，字母 ligature 虽然在字幕文件里没用到，但起码渲染器是支持的；但渲染器不支持 frac 特性，压根不可能调出来 dnom 和 numr 下的字图。

**Comment by MIRIMIRIM** [comment]
这个我得看看pyftsubset有没有提供直接的支持，如果没有的话可能暂时不会去实现
