### ISSUE TITLE
Aegisub调用子集化后的字体，竖排显示失效的问题

### ISSUE THREAD

**Issue by William-LSY** [AmusementClub/AssFontSubset#15]
![01](https://github.com/AmusementClub/AssFontSubset/assets/89622661/01d9643b-ef61-4468-9640-b0fdec2c2321)
![02](https://github.com/AmusementClub/AssFontSubset/assets/89622661/c56e426e-335b-478a-9393-3a01b26b6067)
![03](https://github.com/AmusementClub/AssFontSubset/assets/89622661/5c15d021-b784-4b44-950e-013c4b7342b8)
![04](https://github.com/AmusementClub/AssFontSubset/assets/89622661/171c0e55-80c8-4037-8705-c3c192ecb83d)
![05](https://github.com/AmusementClub/AssFontSubset/assets/89622661/7aa5c8e5-bd3c-46b9-94a9-e74a0f18c25d)
![06](https://github.com/AmusementClub/AssFontSubset/assets/89622661/1db41522-9698-4fb0-b5b5-3203f48d4314)
![07](https://github.com/AmusementClub/AssFontSubset/assets/89622661/2930b6a0-9094-4183-b5b0-e97d4c0b4747)
![08](https://github.com/AmusementClub/AssFontSubset/assets/89622661/2d163ec5-1eec-4189-a4f4-7a7285a722c7)
![09](https://github.com/AmusementClub/AssFontSubset/assets/89622661/c8825911-f41e-4af7-91d2-92fb5b8a7329)

使用最新版的Release程序子集化后的字体，Aegisub调用时竖排字体失效，上图中我用的是【方正兰亭粗黑_GBK】这个字体，其他字体也试过，也出现同样的问题，不知是不是我哪里配置错误，还是版本问题什么的
[方正兰亭粗黑_GBK.zip](https://github.com/AmusementClub/AssFontSubset/files/15481161/_GBK.zip)

**Comment by MIRIMIRIM** [comment]
afs用的是v2.0.0-b5还是v1.2.4.1

**Comment by William-LSY** [comment]
用的是v1.2.4.1

**Comment by William-LSY** [comment]
> afs用的是v2.0.0-b5还是v1.2.4.1

用的是v1.2.4.1

**Comment by William-LSY** [comment]
经测试，是fonttools的4.52.4的版本问题，回退到4.44.0版本后，上述问题已解决

**Comment by MIRIMIRIM** [comment]
问题无法复现，而且建议fonttools更新到最新版本使用。

**Comment by MIRIMIRIM** [comment]
[v2.0.3](https://github.com/AmusementClub/AssFontSubset/releases/tag/v2.0.3) 修复了这个问题，fonttools 升至最新版本后子集化，vsfilter 也可以正确显示竖排

**Comment by William-LSY** [comment]
> [v2.0.3](https://github.com/AmusementClub/AssFontSubset/releases/tag/v2.0.3) 修复了这个问题，fonttools 升至最新版本后子集化，vsfilter 也可以正确显示竖排

fonttools和AssFontSubset均已更新至最新版，测时候未发现问题，VSFilter滤镜下竖排显示正常，感谢解答🙏
