### ISSUE TITLE
子集化时某些所需的字体文件被忽略了

### ISSUE THREAD

**Issue by braxiong** [AmusementClub/AssFontSubset#17]
第72行开始的MuzaiPixel没能被子集化，类似的情况其他文件也有

[[DBD-Raws][Digimon Adventure 02 The Beginning][1080P][BDRip][HEVC-10bit][FLAC].sc.txt](https://github.com/user-attachments/files/16400257/DBD-Raws.Digimon.Adventure.02.The.Beginning.1080P.BDRip.HEVC-10bit.FLAC.sc.txt)
[[DBD-Raws][Digimon Adventure 02 The Beginning][1080P][BDRip][HEVC-10bit][FLAC].tc.txt](https://github.com/user-attachments/files/16400258/DBD-Raws.Digimon.Adventure.02.The.Beginning.1080P.BDRip.HEVC-10bit.FLAC.tc.txt)

**Comment by MIRIMIRIM** [comment]
请先尝试使用 https://github.com/AmusementClub/AssFontSubset/actions/runs/10025738761 处理，如果仍能复现，若方便麻烦提供一下原始字幕和子集化时使用的字体包，如果字体包太大可以上传到任意非网赚网盘。

**Comment by braxiong** [comment]
> 请先尝试使用 https://github.com/AmusementClub/AssFontSubset/actions/runs/10025738761 处理，如果仍能复现，若方便麻烦提供一下原始字幕和子集化时使用的字体包，如果字体包太大可以上传到任意非网赚网盘。

使用该版本仍然不行，我不放入MuzaiPixel这个字体，软件不会进行报错，放入到fonts目录，也不会对它进行子集化。
字幕文件就是1楼两个，以下为字体文件打包(.zip后缀删掉然后7z解压)
麻烦大佬了
[fonts.7z.001.zip](https://github.com/user-attachments/files/16400942/fonts.7z.001.zip)
[fonts.7z.002.zip](https://github.com/user-attachments/files/16400944/fonts.7z.002.zip)
[fonts.7z.003.zip](https://github.com/user-attachments/files/16400945/fonts.7z.003.zip)
[fonts.7z.004.zip](https://github.com/user-attachments/files/16400946/fonts.7z.004.zip)
[fonts.7z.005.zip](https://github.com/user-attachments/files/16400947/fonts.7z.005.zip)

**Comment by MIRIMIRIM** [comment]
https://github.com/AmusementClub/AssFontSubset/actions/runs/10127845067  试一下这个 build

**Comment by braxiong** [comment]
> https://github.com/AmusementClub/AssFontSubset/actions/runs/10127845067 试一下这个 build

用这版可以了，感谢
