### ISSUE TITLE
otf 字体竖排时子集化后，字体大小在 vsfilter 中显示不正常

### ISSUE THREAD

**Issue by dantiewan** [AmusementClub/AssFontSubset#2]
经测试，otf格式的字体在Aegisub调用时如果加上@（即将字幕竖过来放置），用AssFontSubset生成的字体会变大，如图
![111](https://user-images.githubusercontent.com/105163957/167304321-148fdacc-b4e3-4b3e-9ba1-d671d088d6c5.jpg)

**Comment by tastysugar** [comment]
已知问题。
推断这是是 vsfilter 系字幕滤镜的问题而非子集化问题。因为很多没有子集化的字体在竖排时也会字号出问题，例如说思源雅黑。该问题应该只影响 vsfilter 系字幕滤镜而不影响 libass。
目前尚未有解决办法。

**Comment by tastysugar** [comment]
关注一下这个问题 https://github.com/libass/libass/issues/619
