### ISSUE TITLE
vsfilter 中竖排破折号显示错误

### ISSUE THREAD

**Issue by tastysugar** [AmusementClub/AssFontSubset#5]
![Snipaste_2023-01-29_00-45-43](https://user-images.githubusercontent.com/37567389/215315398-092b7a9e-d005-4087-8c89-a2a877c0d05b.jpg)
mpv 显示正常，potplayer 和 mpv-be 显示错误

mpv version: 
```
mpv 0.34.0-551-gf594482451 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Sun Oct 30 12:27:44 2022
FFmpeg library versions:
   libavutil       57.39.101
   libavcodec      59.51.100
   libavformat     59.34.101
   libswscale      6.8.112
   libavfilter     8.49.101
   libswresample   4.9.100
FFmpeg version: git-2022-10-29-01b9abd77
```

Potplayer Version: 221102

MPC-BE Verions: 1.6.4 git 2022.09.07 - bdba5042a

Sample ass file
[[BeanSub&LoliHouse] Vinland Saga S2 - 01 [WebRip 1080p HEVC-10bit AAC ASSx2].SC.txt](https://github.com/tastysugar/AssFontSubset/files/10529389/BeanSub.LoliHouse.Vinland.Saga.S2.-.01.WebRip.1080p.HEVC-10bit.AAC.ASSx2.SC.txt)

**Comment by braxiong** [comment]
ass字幕里@代表竖排，精简后的字体体积小于某个阈值后，@这个参数就不会生效，包括字体也不会变成定义的字体，这个问题好像目前没什么解法。。。。我也发现这个问题很久了

**Comment by MIRIMIRIM** [comment]
https://www.unicode.org/reports/tr50/
这个我现在推测是一般横排用俩 em dash，em dash 不应该用于竖排，竖排推荐换 \uFE31（VERTICAL EM DASH）
